// MFCActiveXControl3.idl : ActiveX 控件项目的类型库源。

// 此文件将由 MIDL 编译器工具处理以
// 产生类型库(MFCActiveXControl3.tlb)，该类型库将成为
// MFCActiveXControl3.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(C84415B3-7473-492F-BA94-A2B53A0C3A6D), version(1.0),
  control ]
library MFCActiveXControl3Lib
{
	importlib(STDOLE_TLB);

	//  CMFCActiveXControl3Ctrl 的主调度接口
	[ 
		uuid(A9D50109-C8C7-47B9-8D27-B9120CFC5B90)	
	]
	dispinterface _DMFCActiveXControl3
	{
		properties:
		methods:

			[id(DISPID_ABOUTBOX)] void AboutBox();
	};

	//  CMFCActiveXControl3Ctrl 的事件调度接口

	[ 
		uuid(3E670333-22C2-4667-8AE6-275C12AA61D7)	
	]
	dispinterface _DMFCActiveXControl3Events
	{
		properties:
			//  事件接口没有任何属性

		methods:
	};

	//  CMFCActiveXControl3Ctrl 的类信息
	[
		uuid(32873A3A-4801-4C91-A23C-CBC3B3A75387)
	]
	coclass MFCActiveXControl3
	{
		[default] dispinterface _DMFCActiveXControl3;
		[default, source] dispinterface _DMFCActiveXControl3Events;
	};

};
